######################################################################
# Automatically generated by qmake (2.01a) po dub 18 19:52:29 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += main.ui
SOURCES += main.cpp
